# Generated by Django 4.2.20 on 2025-05-26 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0002_remove_chatroom_name_chatroom_user1_chatroom_user2"),
    ]

    operations = [
        migrations.RenameField(
            model_name="message",
            old_name="content",
            new_name="content_for_receiver",
        ),
        migrations.AddField(
            model_name="message",
            name="content_for_sender",
            field=models.TextField(default="test"),
            preserve_default=False,
        ),
    ]
