# Generated by Django 4.2.20 on 2025-05-26 10:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0004_remove_userprofile_encrypted_private_key_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="userprofile",
            name="iv",
        ),
    ]
