# Generated by Django 4.2.20 on 2025-06-01 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0005_remove_userprofile_iv"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="encrypted_private_key",
            field=models.TextField(blank=True, null=True),
        ),
    ]
