# Generated by Django 4.2.20 on 2025-06-01 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0006_userprofile_encrypted_private_key"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="iv",
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="name",
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="surname",
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
    ]
