# Generated by Django 4.2.20 on 2025-06-01 14:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0007_userprofile_iv_userprofile_name_userprofile_surname"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="userprofile",
            name="name",
        ),
        migrations.RemoveField(
            model_name="userprofile",
            name="surname",
        ),
    ]
